import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.title': 'STONE IDOL',
    'header.subtitle': 'Mini Kdrama Mochis',
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.about': 'About',
    
    // Hero Section
    'hero.title': 'Mini Kdrama Mochis',
    'hero.subtitle': 'Create your Mochis box with your favorite Kdramas!',
    'hero.tagline': 'Your box will be unique!',
    'hero.description': 'I create your favorite characters inspired by what matters most to you: your Safe Place, what reassures you and helps you manage everyday life.',
    'hero.mainDescription': 'You too, have you discovered Kdramas? Are you watching more and more? And some have touched you more than others?',
    'hero.personalDescription': 'Tell me which ones are your favorites, I can create your box. It will be unique, made according to your preferences!',
    'hero.questionDescription': 'Each mochi is unique and reflects the chosen Kdrama!',
    'hero.giftDescription': 'In my box, there is the Mochi referencing my first Kdrama: "King the Land", the one that will mark me forever "Itaewon Class" and 7 others of my favorites like "Weak Hero Class", "Reply 1988" or "When Life Gives You Tangerines".',
    'hero.noteDescription': 'Note: I don\'t use AI to create my Mochis.',
    'hero.callToAction': 'Which Kdramas do you want to remember forever?',
    'hero.boxDescription': 'Each Mochis box comes with its description including series reference, main actors and year.',
    'hero.warningNotEdible': 'Warning: Mochis are not edible, they are decorations.',
    'hero.photoPlaceholder': 'Photo coming soon',
    'hero.shopButton': 'Shop Surprise Packs',
    'hero.exploreButton': 'Explore Goodies',
    'hero.cardsPerPack': 'Cards per pack',
    'hero.series': 'Cadeaux personnalisés',
    'hero.surprise': 'Surprise',
    
    // Shop Section
    'shop.title': 'Mini Kdrama Mochis',
    'shop.subtitle': 'Create your unique box!',
    'shop.mochisBoxName': 'My Mochis Box',
    'shop.mochisBoxDesc': '9 unique Mochis inspired by your favorite Kdramas, with description card',
    'shop.kdramaChoicesLabel': 'Which Kdramas do you want in your box? (9 choices)',
    'shop.kdramaChoicesPlaceholder': 'Example: Crash Landing on You, Itaewon Class, Reply 1988, True Beauty, Weak Hero Class, When Life Gives You Tangerines...',
    'shop.kdramaChoicesHint': 'List 9 Kdramas of your choice. Each mochi will be unique and reflect the chosen drama!',
    'shop.kdramaRequired': 'Kdramas required',
    'shop.kdramaRequiredMessage': 'Please enter your 9 favorite Kdramas to create your personalized box.',
    'shop.quantity': 'Quantity',
    'shop.addToCart': 'Add to Cart',
    'shop.giftCardName': 'Gift Card',
    'shop.giftCardDesc': 'Offer a personalized Mochis box! The recipient will choose their 9 favorite Kdramas.',
    'shop.recipientNameLabel': 'Recipient name (optional)',
    'shop.recipientNamePlaceholder': 'Name of the person who will receive the gift',
    'shop.addPhysicalCard': 'Add a physical gift card',
    'shop.physicalCardDesc': 'A beautiful printed card to offer with the gift voucher',
    'shop.physicalCardName': 'Physical Gift Card',
    'shop.charactersLabel': 'Number of characters:',
    'shop.supportLabel': 'Support:',
    'shop.tshirtSizeLabel': 'T-shirt size:',
    'shop.chooseNumber': 'Choose number',
    'shop.chooseSupport': 'Choose support',
    'shop.chooseSize': 'Choose size',
    'shop.chooseFrameColor': 'Choose frame color',
    'shop.frameColorLabel': 'Frame color:',
    'shop.whiteFrame': 'White frame',
    'shop.blackFrame': 'Black frame',
    'shop.startingFrom': 'Starting from €',
    'shop.character1': '1 character',
    'shop.characters2': '2 characters',
    'shop.characters3': '3 characters',
    'shop.characters4': '4 characters',
    'shop.family': 'Family (max. 5 characters)',
    'shop.paperNoFrame': '250g A4 paper without frame',
    'shop.paperWithFrame': '250g A4 paper with frame',
    'shop.petitToteBag': 'Small Tote Bag (28cm x 30cm)',
    'shop.toteBag': 'Large Tote Bag (38cm x 41cm, cotton)',
    'shop.backpack': 'Backpack (35cm x 40cm, cotton)',
    'shop.tshirt': 'T-shirt',
    'shop.description': 'Découvrez nos Mini Kdrama Mochis personnalisés inspirés de vos séries coréennes préférées.',
    'shop.surprisePacks': 'Surprise Card Packs',
    'shop.goodies': 'Goodies Kdrama',
    'shop.surprisePackName': 'Stone Idol Surprise Pack',
    'shop.surprisePackDesc': 'Mystery pack containing 3 exclusive Stone Idol collectible cards',
    'shop.oldAddToCart': 'Add to Cart',
    'shop.selectDesign': 'Select Design',
    'shop.selectSize': 'Select Size',
    'shop.cardsCollectionTitle': 'Stone Idol Collection cards',
    'shop.cardsCollectionSubtitle': 'They all became part of our lives at some point',
    'shop.goodiesTitle': 'Goodies Kdrama',
    'shop.goodiesSubtitle': 'Choisissez votre création personnalisée parmi nos designs uniques !',
    
    // Products
    'product.toteBag': 'Stone Idol Tote Bag',
    'product.toteBagDesc': '100% cotton, Size: 38cm x 42cm',
    'product.tshirt': 'Stone Idol T-Shirt',
    'product.tshirtDesc': 'Cotton and polyester blend',
    'product.backpack': 'Stone Idol Backpack',
    'product.backpackDesc': '100% cotton, Size: 38cm x 40cm',
    'product.pictureFrame': 'Stone Idol Picture Frame',
    'product.pictureFrameDesc': 'Size: 10cm x 15cm',
    'product.handkerchiefSet': 'Fabric Handkerchief Set',
    'product.handkerchiefSetDesc': '100% cotton, Size: 23cm x 23cm with carrying pouch',
    
    'cart.itemAdded': 'Added to cart!',
    'cart.addedToCart': 'has been added to your cart.',
    'cart.empty': 'Your cart is empty',
    'cart.shipping': 'Shipping',
    'cart.itemsTotal': 'Items',
    'cart.country': 'Destination Country',
    'cart.calculate': 'Calculate',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.freeShipping': 'Free Shipping!',
    'cart.checkout': 'Proceed to Checkout',
    
    // Upload
    'upload.addFile': 'Add photo or PDF',
    'upload.downloadFile': 'Upload file',
    'upload.success': 'File uploaded!',
    'upload.uploaded': 'has been uploaded successfully.',
    'upload.error': 'Upload error',
    'upload.invalidFormat': 'Please select an image (JPG, PNG) or PDF file.',
    'upload.required': 'File required',
    'upload.requiredMessage': 'Please upload a photo or PDF file to customize your mochi.',
    'upload.instructions': 'Instructions for your photos:',
    'upload.frontFace': 'Add images of people from the front',
    'upload.fullBody': 'Full body photos (entire body visible)',
    'upload.quality': 'Good quality and lighting',
    
    // Collections
    'collections.viewButton': 'View collections',
    
    // Character Choices
    'choices.title': 'Choose your characters',
    'choices.placeholder': 'Enter character numbers (e.g., 1, 5, 12)',
    'choices.example': 'Example: 1, 5, 12 for characters 1, 5 and 12',
    'choices.required': 'Character numbers required',
    'choices.requiredMessage': 'Please indicate the character numbers you want to order.',
    
    // Shipping Calculator
    'shipping.title': 'Shipping Calculator',
    'shipping.country': 'Destination Country',
    'shipping.postalCode': 'Postal Code (optional)',
    'shipping.calculate': 'Calculate',
    'shipping.cost': 'Shipping Cost',
    'shipping.free': 'Free Shipping!',
    'shipping.emptyCart': 'Add items to cart to calculate shipping',
    'shipping.deliveryTime': 'Estimated Delivery Time',
    
    'footer.description': 'Mini Kdrama Mochis personnalisés inspirés de vos séries coréennes préférées. Des cadeaux uniques fait main.',
    'footer.customerService': 'Customer Service',
    'footer.connectWithUs': 'Connect With Us',
    'footer.returnPolicy': 'Return Policy',
    'footer.shippingInfo': 'Shipping Info',
    'footer.sizeGuide': 'Size Guide',
    'footer.faq': 'FAQ',
    'footer.email': 'Email:',
    'footer.tiktok': 'TikTok:',
    'footer.company': 'Company:',
    'footer.siren': 'SIREN:',
    'footer.hosting': 'Hosting:',
    'footer.copyright': '© 2024 Stone Idol. All rights reserved.',
    'footer.legalTerms': 'Legal Terms',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.returns': 'Returns',
    
    // Return Policy
    'return.title': 'Return & Refund Policy',
    'return.subtitle': 'We want you to be fully happy with your order! If there\'s a problem, we\'re here to help.',
    'return.canReturnTitle': 'What can be returned?',
    'return.canReturnIntro': 'You can return:',
    'return.tshirtsBags': 'T-shirts and bags:',
    'return.tshirtsBagsDesc': 'must be unused, unwashed, and in original condition',
    'return.cards': 'Cards (greeting/postcards):',
    'return.cardsDesc': 'must be unused, undamaged, and in original packaging',
    'return.timeLimit': 'You have 14 days from the delivery date to request a return.',
    'return.cannotReturnTitle': 'What can\'t be returned?',
    'return.cannotReturnWorn': 'Items that have been worn, washed, or used',
    'return.cannotReturnCustom': 'Custom or personalized products',
    'return.cannotReturnSale': 'Items on sale or promotion',
    'return.cannotReturnDamaged': 'Damaged items caused by misuse',
    'return.howToReturnTitle': 'How to return?',
    'return.howToReturnIntro': 'Email us at',
    'return.howToReturnWith': 'with:',
    'return.orderNumber': 'Your order number',
    'return.returnReason': 'The reason for return',
    'return.instructionsSent': 'We\'ll send you the return instructions and address',
    'return.shipWithin': 'Ship the item back within 7 days of approval',
    'return.shippingNote': 'Return shipping costs are your responsibility, unless the product is defective or we made a mistake.',
    'return.refundTitle': 'Refund process',
    'return.refundReceived': 'Once we receive and inspect your item, we\'ll confirm by email',
    'return.refundTiming': 'If approved, you\'ll get your refund within 5–10 business days',
    'return.refundMethod': 'Refunds go back to your original payment method',
    'return.contactTitle': 'Need help or have a question? Contact us anytime at',
    
    // Size Guide
    'size.title': 'Size Guide',
    'size.subtitle': 'Find your perfect fit with our international sizing chart',
    'size.chartTitle': 'International Size Chart',
    'size.international': 'International',
    'size.france': 'France (FR)',
    'size.korea': 'Korea (KR)',
    'size.uk': 'UK',
    'size.us': 'US',
    'size.notesTitle': 'Sizing Notes',
    'size.note1': 'All measurements are approximate and may vary slightly depending on the specific item.',
    'size.note2': 'If you\'re between sizes, we recommend choosing the larger size for a more comfortable fit.',
    'size.note3': 'For any sizing questions, please contact us at stone.idol@yahoo.com',
  },
  fr: {
    // Header
    'header.title': 'STONE IDOL',
    'header.subtitle': 'Mini Kdrama Mochis',
    'nav.home': 'Accueil',
    'nav.shop': 'Boutique',
    'nav.about': 'À propos',
    
    // Hero Section
    'hero.title': 'Mini Kdrama Mochis',
    'hero.subtitle': 'Crée ta boite de Mochis avec tes Kdramas préférés!',
    'hero.tagline': 'Ta boite sera unique!',
    'hero.description': 'Je crée vos personnages préférés en m\'inspirant de ce qui compte le plus pour vous: votre Safe Place, ce qui vous rassure et vous permet de gérer le quotidien.',
    'hero.mainDescription': 'Toi aussi, tu as découvert les Kdramas? Tu en regardes toujours plus? Et certains t\'ont marqué plus que d\'autres?',
    'hero.personalDescription': 'Dis moi quels sont tes préférés, je pourrai créer ta boite. Elle sera unique, faite en fonction de tes préférences!',
    'hero.questionDescription': 'Chaque mochi est unique et à l\'image du Kdrama choisi!',
    'hero.giftDescription': 'Dans ma boite, il y a le Mochi référence à mon premier Kdrama: "King the Land", celui qui me marquera pour toujours "Itaewon Class" et 7 autres de mes coups de coeur comme "Weak Hero Class", "Reply 1988" ou encore "When Life Gives You Tangerines".',
    'hero.noteDescription': 'NB: je n\'utilise pas d\'IA pour créer mes Mochis.',
    'hero.callToAction': 'De quels Kdramas veux-tu te souvenir pour toujours?',
    'hero.boxDescription': 'Chaque boite de Mochis est accompagnée de son descriptif avec Référence de la série, acteurs principaux et année.',
    'hero.warningNotEdible': 'Attention: les Mochis ne sont pas comestibles, il s\'agit de décorations.',
    'hero.photoPlaceholder': 'Photo à venir',
    'hero.shopButton': 'Acheter des Packs Surprise',
    'hero.exploreButton': 'Explorer les Goodies',
    'hero.cardsPerPack': 'Cartes par pack',
    'hero.series': 'Cadeaux personnalisés',
    'hero.surprise': 'Surprise',
    
    // Shop Section
    'shop.title': 'Mini Kdrama Mochis',
    'shop.subtitle': 'Crée ta boite unique!',
    'shop.mochisBoxName': 'Ma boite de Mochis',
    'shop.mochisBoxDesc': '9 Mochis uniques inspirés de tes Kdramas préférés, avec carte descriptive',
    'shop.kdramaChoicesLabel': 'Quels Kdramas veux-tu dans ta boite? (9 choix)',
    'shop.kdramaChoicesPlaceholder': 'Exemple: Crash Landing on You, Itaewon Class, Reply 1988, True Beauty, Weak Hero Class, When Life Gives You Tangerines...',
    'shop.kdramaChoicesHint': 'Indique 9 Kdramas de ton choix. Chaque mochi sera unique et à l\'image du drama choisi!',
    'shop.kdramaRequired': 'Kdramas requis',
    'shop.kdramaRequiredMessage': 'Merci d\'indiquer tes 9 Kdramas préférés pour créer ta boite personnalisée.',
    'shop.quantity': 'Quantité',
    'shop.addToCart': 'Ajouter au Panier',
    'shop.giftCardName': 'Bon Cadeau',
    'shop.giftCardDesc': 'Offre une boite de Mochis personnalisée! Le destinataire choisira ses 9 Kdramas préférés.',
    'shop.recipientNameLabel': 'Nom du destinataire (optionnel)',
    'shop.recipientNamePlaceholder': 'Nom de la personne qui recevra le cadeau',
    'shop.addPhysicalCard': 'Ajouter une carte cadeau physique',
    'shop.physicalCardDesc': 'Une jolie carte imprimée à offrir avec le bon cadeau',
    'shop.physicalCardName': 'Carte Cadeau Physique',
    'shop.charactersLabel': 'Nombre de personnages:',
    'shop.supportLabel': 'Support:',
    'shop.tshirtSizeLabel': 'Taille du T-shirt:',
    'shop.chooseNumber': 'Choisir le nombre',
    'shop.chooseSupport': 'Choisir le support',
    'shop.chooseSize': 'Choisir la taille',
    'shop.chooseFrameColor': 'Choisir la couleur du cadre',
    'shop.frameColorLabel': 'Couleur du cadre:',
    'shop.whiteFrame': 'Cadre blanc',
    'shop.blackFrame': 'Cadre noir',
    'shop.startingFrom': 'À partir de €',
    'shop.character1': '1 personnage',
    'shop.characters2': '2 personnages',
    'shop.characters3': '3 personnages',
    'shop.characters4': '4 personnages',
    'shop.family': 'Famille (max. 5 personnages)',
    'shop.paperNoFrame': 'Papier 250g A4 sans cadre',
    'shop.paperWithFrame': 'Papier 250g A4 avec cadre',
    'shop.petitToteBag': 'Petit Tote Bag (28cm x 30cm, coton)',
    'shop.toteBag': 'Grand Tote Bag (38cm x 41cm, coton)',
    'shop.backpack': 'Backpack (35cm x 40cm, coton)',
    'shop.tshirt': 'T-shirt',
    'shop.description': 'Découvrez nos Mini Kdrama Mochis personnalisés inspirés de vos séries coréennes préférées.',
    'shop.surprisePacks': 'Packs de Cartes Surprise',
    'shop.goodies': 'Goodies Kdrama',
    'shop.surprisePackName': 'Pack Surprise Stone Idol',
    'shop.surprisePackDesc': 'Pack mystère contenant 3 cartes de collection Stone Idol exclusives',
    'shop.oldAddToCart': 'Ajouter au Panier',
    'shop.selectDesign': 'Sélectionner le Design',
    'shop.selectSize': 'Sélectionner la Taille',
    'shop.cardsCollectionTitle': 'Cartes de Collection Stone Idol',
    'shop.cardsCollectionSubtitle': 'Ils ont tous fait partie de nos vies à un moment donné',
    'shop.goodiesTitle': 'Goodies Kdrama',
    'shop.goodiesSubtitle': 'Choisis ta création personnalisée parmi nos designs uniques !',
    
    // Products
    'product.toteBag': 'Sac Tote Stone Idol',
    'product.toteBagDesc': '100% coton, Taille : 38cm x 42cm',
    'product.tshirt': 'T-Shirt Stone Idol',
    'product.tshirtDesc': 'Mélange coton et polyester',
    'product.backpack': 'Sac à Dos Stone Idol',
    'product.backpackDesc': '100% coton, Taille : 38cm x 40cm',
    'product.pictureFrame': 'Cadre Photo Stone Idol',
    'product.pictureFrameDesc': 'Taille : 10cm x 15cm',
    'product.handkerchiefSet': 'Set de Mouchoirs en Tissu',
    'product.handkerchiefSetDesc': '100% coton, Taille : 23cm x 23cm avec pochette de transport',
    
    // Cart
    'cart.itemAdded': 'Ajouté au panier !',
    'cart.addedToCart': 'a été ajouté à votre panier.',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.shipping': 'Frais de livraison',
    'cart.itemsTotal': 'Articles',
    'cart.country': 'Pays de destination',
    'cart.calculate': 'Calculer',
    'cart.subtotal': 'Sous-total',
    'cart.total': 'Total',
    'cart.freeShipping': 'Livraison gratuite !',
    'cart.checkout': 'Passer la commande',
    
    // Upload
    'upload.addFile': 'Ajouter photo ou PDF',
    'upload.downloadFile': 'Télécharger un fichier',
    'upload.success': 'Fichier téléchargé !',
    'upload.uploaded': 'a été téléchargé avec succès.',
    'upload.error': 'Erreur de téléchargement',
    'upload.invalidFormat': 'Veuillez sélectionner une image (JPG, PNG) ou un fichier PDF.',
    'upload.required': 'Fichier requis',
    'upload.requiredMessage': 'Veuillez télécharger une photo ou un fichier PDF pour personnaliser votre mochi.',
    'upload.instructions': 'Instructions pour vos photos :',
    'upload.frontFace': 'Ajoutez des images de personnes de face',
    'upload.fullBody': 'Photos en pied (corps entier visible)',
    'upload.quality': 'Qualité correcte et bonne luminosité',
    
    // Collections
    'collections.viewButton': 'Voir les collections',
    
    // Character Choices
    'choices.title': 'Choisis ton/tes personnages',
    'choices.placeholder': 'Indique les numéros (ex: 1, 5, 12)',
    'choices.example': 'Exemple: 1, 5, 12 pour les personnages 1, 5 et 12',
    'choices.required': 'Numéros de personnages requis',
    'choices.requiredMessage': 'Veuillez indiquer les numéros des personnages que vous souhaitez commander.',
    
    // Shipping Calculator
    'shipping.title': 'Calculateur de Livraison',
    'shipping.country': 'Pays de destination',
    'shipping.postalCode': 'Code postal (optionnel)',
    'shipping.calculate': 'Calculer',
    'shipping.cost': 'Frais de livraison',
    'shipping.free': 'Livraison gratuite !',
    'shipping.emptyCart': 'Ajoutez des articles au panier pour calculer les frais de livraison',
    'shipping.deliveryTime': 'Délai de livraison estimé',
    
    'footer.description': 'Mini Kdrama Mochis personnalisés inspirés de vos séries coréennes préférées. Des cadeaux uniques fait main.',
    'footer.customerService': 'Service Client',
    'footer.connectWithUs': 'Restez Connectés',
    'footer.returnPolicy': 'Politique de Retour',
    'footer.shippingInfo': 'Infos Livraison',
    'footer.sizeGuide': 'Guide des Tailles',
    'footer.faq': 'FAQ',
    'footer.email': 'Email :',
    'footer.tiktok': 'TikTok :',
    'footer.company': 'Société :',
    'footer.siren': 'SIREN :',
    'footer.hosting': 'Hébergement :',
    'footer.copyright': '© 2024 Stone Idol. Tous droits réservés.',
    'footer.legalTerms': 'Mentions Légales',
    'footer.privacyPolicy': 'Politique de Confidentialité',
    'footer.returns': 'Retours',
    
    // Return Policy
    'return.title': 'Politique de Retour et Remboursement',
    'return.subtitle': 'Nous voulons que vous soyez entièrement satisfait de votre commande ! S\'il y a un problème, nous sommes là pour vous aider.',
    'return.canReturnTitle': 'Que peut-on retourner ?',
    'return.canReturnIntro': 'Vous pouvez retourner :',
    'return.tshirtsBags': 'T-shirts et sacs :',
    'return.tshirtsBagsDesc': 'doivent être non utilisés, non lavés et dans leur état d\'origine',
    'return.cards': 'Cartes (vœux/cartes postales) :',
    'return.cardsDesc': 'doivent être non utilisées, non endommagées et dans leur emballage d\'origine',
    'return.timeLimit': 'Vous avez 14 jours à compter de la date de livraison pour demander un retour.',
    'return.cannotReturnTitle': 'Que ne peut-on pas retourner ?',
    'return.cannotReturnWorn': 'Articles qui ont été portés, lavés ou utilisés',
    'return.cannotReturnCustom': 'Produits personnalisés ou sur mesure',
    'return.cannotReturnSale': 'Articles en solde ou en promotion',
    'return.cannotReturnDamaged': 'Articles endommagés par une mauvaise utilisation',
    'return.howToReturnTitle': 'Comment retourner ?',
    'return.howToReturnIntro': 'Envoyez-nous un email à',
    'return.howToReturnWith': 'avec :',
    'return.orderNumber': 'Votre numéro de commande',
    'return.returnReason': 'La raison du retour',
    'return.instructionsSent': 'Nous vous enverrons les instructions de retour et l\'adresse',
    'return.shipWithin': 'Renvoyez l\'article dans les 7 jours suivant l\'approbation',
    'return.shippingNote': 'Les frais de retour sont à votre charge, sauf si le produit est défectueux ou si nous avons fait une erreur.',
    'return.refundTitle': 'Processus de remboursement',
    'return.refundReceived': 'Une fois que nous recevons et inspectons votre article, nous vous confirmerons par email',
    'return.refundTiming': 'Si approuvé, vous recevrez votre remboursement sous 5 à 10 jours ouvrables',
    'return.refundMethod': 'Les remboursements sont effectués sur votre mode de paiement d\'origine',
    'return.contactTitle': 'Besoin d\'aide ou vous avez une question ? Contactez-nous à tout moment à',
    
    // Size Guide
    'size.title': 'Guide des Tailles',
    'size.subtitle': 'Trouvez votre taille parfaite avec notre tableau de correspondance international',
    'size.chartTitle': 'Tableau International des Tailles',
    'size.international': 'International',
    'size.france': 'France (FR)',
    'size.korea': 'Corée (KR)',
    'size.uk': 'UK',
    'size.us': 'US',
    'size.notesTitle': 'Notes sur les Tailles',
    'size.note1': 'Toutes les mesures sont approximatives et peuvent varier légèrement selon l\'article spécifique.',
    'size.note2': 'Si vous hésitez entre deux tailles, nous recommandons de choisir la plus grande pour un ajustement plus confortable.',
    'size.note3': 'Pour toute question concernant les tailles, veuillez nous contacter à stone.idol@yahoo.com',
  },
  ko: {
    // Header
    'header.title': 'STONE IDOL',
    'header.subtitle': '맞춤 치비 선물',
    'nav.home': '홈',
    'nav.shop': '쇼핑',
    'nav.about': '소개',
    
    // Hero Section
    'hero.title': 'Mini Kdrama Mochis',
    'hero.subtitle': '좋아하는 K드라마로 나만의 모찌 박스를 만들어보세요!',
    'hero.tagline': '너만의 박스가 될 거야!',
    'hero.description': '당신에게 가장 소중한 것, 즉 당신의 Safe Place에서 영감을 받아 당신이 좋아하는 캐릭터들을 만듭니다.',
    'hero.mainDescription': '너도 K드라마를 발견했어? 점점 더 많이 보고 있어? 그리고 어떤 드라마가 더 인상 깊었어?',
    'hero.personalDescription': '좋아하는 드라마가 뭔지 말해줘, 너만의 박스를 만들어줄게. 네 취향에 맞춰 유일무이한 박스가 될 거야!',
    'hero.questionDescription': '각 모찌는 선택한 K드라마를 반영해서 유일무이해!',
    'hero.giftDescription': '내 박스에는 첫 K드라마 "King the Land"를 참조한 모찌가 있고, 영원히 기억될 "이태원 클라쓰", 그리고 "약한영웅 Class 1", "응답하라 1988", "인생이 레몬을 줄 때" 같은 7개의 다른 최애작들이 있어.',
    'hero.noteDescription': '참고: 모찌를 만들 때 AI를 사용하지 않습니다.',
    'hero.callToAction': '어떤 K드라마를 영원히 기억하고 싶어?',
    'hero.boxDescription': '각 모찌 박스에는 시리즈 참조, 주요 배우 및 연도가 포함된 설명서가 함께 제공됩니다.',
    'hero.warningNotEdible': '주의: 모찌는 먹을 수 없으며 장식용입니다.',
    'hero.photoPlaceholder': '곧 사진이 올 예정',
    'hero.shopButton': '서프라이즈 팩 쇼핑',
    'hero.exploreButton': '굿즈 탐색',
    'hero.cardsPerPack': '팩당 카드 수',
    'hero.series': '케이드라마 시리즈',
    'hero.surprise': '서프라이즈',
    
    // Shop Section
    'shop.title': '미니 K드라마 모찌',
    'shop.subtitle': '나만의 박스를 만들어보세요!',
    'shop.mochisBoxName': '나의 모찌 박스',
    'shop.mochisBoxDesc': '좋아하는 K드라마에서 영감을 받은 9개의 유니크한 모찌, 설명 카드 포함',
    'shop.kdramaChoicesLabel': '박스에 어떤 K드라마를 넣고 싶으세요? (9개 선택)',
    'shop.kdramaChoicesPlaceholder': '예: 사랑의 불시착, 이태원 클라쓰, 응답하라 1988, 여신강림, 약한영웅 Class 1...',
    'shop.kdramaChoicesHint': '원하는 K드라마 9개를 적어주세요. 각 모찌는 선택한 드라마를 반영해 유일무이하게 만들어집니다!',
    'shop.kdramaRequired': 'K드라마 필수',
    'shop.kdramaRequiredMessage': '맞춤 박스를 만들기 위해 좋아하는 K드라마 9개를 입력해주세요.',
    'shop.quantity': '수량',
    'shop.addToCart': '장바구니에 추가',
    'shop.giftCardName': '기프트 카드',
    'shop.giftCardDesc': '맞춤 모찌 박스를 선물하세요! 받는 사람이 좋아하는 K드라마 9개를 선택할 수 있습니다.',
    'shop.recipientNameLabel': '받는 사람 이름 (선택사항)',
    'shop.recipientNamePlaceholder': '선물 받을 사람의 이름',
    'shop.addPhysicalCard': '실물 기프트 카드 추가',
    'shop.physicalCardDesc': '기프트 카드와 함께 제공되는 예쁜 인쇄 카드',
    'shop.physicalCardName': '실물 기프트 카드',
    'shop.charactersLabel': '캐릭터 수:',
    'shop.supportLabel': '서포트:',
    'shop.tshirtSizeLabel': '티셔츠 사이즈:',
    'shop.chooseNumber': '수량 선택',
    'shop.chooseSupport': '서포트 선택',
    'shop.chooseSize': '사이즈 선택',
    'shop.chooseFrameColor': '프레임 색상 선택',
    'shop.frameColorLabel': '프레임 색상:',
    'shop.whiteFrame': '화이트 프레임',
    'shop.blackFrame': '블랙 프레임',
    'shop.startingFrom': '시작 가격 €',
    'shop.character1': '1 캐릭터',
    'shop.characters2': '2 캐릭터',
    'shop.characters3': '3 캐릭터',
    'shop.characters4': '4 캐릭터',
    'shop.family': '가족 (최대 5 캐릭터)',
    'shop.paperNoFrame': '250g A4 용지 (프레임 없음)',
    'shop.paperWithFrame': '250g A4 용지 (프레임 포함)',
    'shop.petitToteBag': '소형 토트백 (28cm x 30cm)',
    'shop.toteBag': '대형 토트백 (38cm x 41cm, 면)',
    'shop.backpack': '백팩 (35cm x 40cm, 면)',
    'shop.tshirt': '티셔츠',
    'shop.description': '좋아하는 시리즈에서 영감을 받은 독점 케이드라마 수집품과 프리미엄 상품을 발견하세요.',
    'shop.surprisePacks': '서프라이즈 카드 팩',
    'shop.goodies': '굿즈',
    'shop.surprisePackName': 'Stone Idol 서프라이즈 팩',
    'shop.surprisePackDesc': '3장의 독점 Stone Idol 수집용 카드가 들어있는 미스터리 팩',
    'shop.oldAddToCart': '장바구니에 추가',
    'shop.selectDesign': '디자인 선택',
    'shop.selectSize': '사이즈 선택',
    'shop.cardsCollectionTitle': 'Stone Idol 컬렉션 카드',
    'shop.cardsCollectionSubtitle': '모두 사랑해요!',
    'shop.goodiesTitle': '스톤 아이돌 굿즈',
    'shop.goodiesSubtitle': '가장 인기 있는 드라마 중에서 좋아하는 것을 선택하세요!',
    
    // Products
    'product.toteBag': 'Stone Idol 토트백',
    'product.toteBagDesc': '100% 코튼, 사이즈: 38cm x 42cm',
    'product.tshirt': 'Stone Idol 티셔츠',
    'product.tshirtDesc': '코튼과 폴리에스터 혼방',
    'product.backpack': 'Stone Idol 백팩',
    'product.backpackDesc': '100% 코튼, 사이즈: 38cm x 40cm',
    'product.pictureFrame': 'Stone Idol 액자',
    'product.pictureFrameDesc': '사이즈: 10cm x 15cm',
    'product.handkerchiefSet': '패브릭 손수건 세트',
    'product.handkerchiefSetDesc': '100% 코튼, 사이즈: 23cm x 23cm 휴대용 파우치 포함',
    
    'cart.itemAdded': '장바구니에 추가됨!',
    'cart.addedToCart': '장바구니에 추가되었습니다.',
    'cart.empty': '장바구니가 비어있습니다',
    'cart.shipping': '배송비',
    'cart.itemsTotal': '상품',
    'cart.country': '배송 국가',
    'cart.calculate': '계산하기',
    'cart.subtotal': '소계',
    'cart.total': '총액',
    'cart.freeShipping': '무료 배송!',
    'cart.checkout': '결제하기',
    
    // Upload
    'upload.addFile': '사진 또는 PDF 추가',
    'upload.downloadFile': '파일 업로드',
    'upload.success': '파일 업로드 완료!',
    'upload.uploaded': '성공적으로 업로드되었습니다.',
    'upload.error': '업로드 오류',
    'upload.invalidFormat': '이미지 파일(JPG, PNG) 또는 PDF 파일을 선택해주세요.',
    'upload.required': '파일 필수',
    'upload.requiredMessage': '치비를 맞춤 제작하려면 사진이나 PDF 파일을 업로드해주세요.',
    'upload.instructions': '사진 안내:',
    'upload.frontFace': '정면 사진을 추가해주세요',
    'upload.fullBody': '전신 사진 (전체 몸이 보이는)',
    'upload.quality': '좋은 화질과 조명',
    
    // Collections
    'collections.viewButton': '컬렉션 보기',
    
    // Character Choices
    'choices.title': '캐릭터 선택하기',
    'choices.placeholder': '번호를 입력하세요 (예: 1, 5, 12)',
    'choices.example': '예시: 1, 5, 12는 캐릭터 1, 5, 12번을 의미합니다',
    'choices.required': '캐릭터 번호 필수',
    'choices.requiredMessage': '주문하려는 캐릭터 번호를 입력해주세요.',
    
    // Shipping Calculator
    'shipping.title': '배송비 계산기',
    'shipping.country': '배송 국가',
    'shipping.postalCode': '우편번호 (선택사항)',
    'shipping.calculate': '계산하기',
    'shipping.cost': '배송비',
    'shipping.free': '무료 배송!',
    'shipping.emptyCart': '배송비 계산을 위해 장바구니에 상품을 추가해주세요',
    'shipping.deliveryTime': '예상 배송 시간',
    
    'footer.description': '당신의 Safe Place에서 영감을 받은 독특한 맞춤 치비 창작. 당신의 이야기를 담은 맞춤형 선물.',
    'footer.customerService': '고객 서비스',
    'footer.connectWithUs': '소셜 미디어',
    'footer.returnPolicy': '반품 정책',
    'footer.shippingInfo': '배송 정보',
    'footer.sizeGuide': '사이즈 가이드',
    'footer.faq': '자주 묻는 질문',
    'footer.email': '이메일:',
    'footer.tiktok': '틱톡:',
    'footer.company': '회사:',
    'footer.siren': 'SIREN:',
    'footer.hosting': '호스팅:',
    'footer.copyright': '© 2024 Stone Idol. 모든 권리 보유.',
    'footer.legalTerms': '법적 조건',
    'footer.privacyPolicy': '개인정보 보호정책',
    'footer.returns': '반품',
    
    // Return Policy
    'return.title': '반품 및 환불 정책',
    'return.subtitle': '주문하신 상품에 완전히 만족하시길 바랍니다! 문제가 있으시면 도와드리겠습니다.',
    'return.canReturnTitle': '반품 가능한 상품은?',
    'return.canReturnIntro': '반품 가능한 상품:',
    'return.tshirtsBags': '티셔츠 및 가방:',
    'return.tshirtsBagsDesc': '미사용, 미세탁, 원래 상태여야 합니다',
    'return.cards': '카드 (인사카드/엽서):',
    'return.cardsDesc': '미사용, 손상되지 않은 원래 포장 상태여야 합니다',
    'return.timeLimit': '배송일로부터 14일 이내에 반품을 요청하실 수 있습니다.',
    'return.cannotReturnTitle': '반품 불가능한 상품은?',
    'return.cannotReturnWorn': '착용, 세탁 또는 사용된 상품',
    'return.cannotReturnCustom': '맞춤 제작 또는 개인화된 제품',
    'return.cannotReturnSale': '세일 또는 프로모션 상품',
    'return.cannotReturnDamaged': '잘못된 사용으로 손상된 상품',
    'return.howToReturnTitle': '반품 방법은?',
    'return.howToReturnIntro': '다음 정보와 함께 이메일을 보내주세요',
    'return.howToReturnWith': '포함 사항:',
    'return.orderNumber': '주문 번호',
    'return.returnReason': '반품 사유',
    'return.instructionsSent': '반품 안내 및 주소를 보내드리겠습니다',
    'return.shipWithin': '승인 후 7일 이내에 상품을 반송해주세요',
    'return.shippingNote': '제품 결함이나 당사 실수가 아닌 경우, 반품 배송비는 고객 부담입니다.',
    'return.refundTitle': '환불 절차',
    'return.refundReceived': '상품을 받아 검수한 후 이메일로 확인해 드립니다',
    'return.refundTiming': '승인되면 5-10 영업일 이내에 환불받으실 수 있습니다',
    'return.refundMethod': '환불은 원래 결제 수단으로 진행됩니다',
    'return.contactTitle': '도움이 필요하거나 질문이 있으신가요? 언제든지 문의하세요',
    
    // Size Guide
    'size.title': '사이즈 가이드',
    'size.subtitle': '국제 사이즈 차트로 완벽한 핏을 찾으세요',
    'size.chartTitle': '국제 사이즈 차트',
    'size.international': '국제',
    'size.france': '프랑스 (FR)',
    'size.korea': '한국 (KR)',
    'size.uk': 'UK',
    'size.us': 'US',
    'size.notesTitle': '사이즈 참고사항',
    'size.note1': '모든 치수는 대략적이며 특정 제품에 따라 약간 다를 수 있습니다.',
    'size.note2': '사이즈 사이에서 고민이시라면, 더 편안한 착용감을 위해 큰 사이즈를 선택하시는 것을 권장합니다.',
    'size.note3': '사이즈에 관한 질문은 stone.idol@yahoo.com으로 문의해주세요',
  }

};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
