// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnczhnzkbrkkkicwpqxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuY3pobnprYnJra2tpY3dwcXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTcyMzAsImV4cCI6MjA2NTgzMzIzMH0.CWw8Rs7tZ377ULP1ivWnnH_yAM9jfAuG48nDJJc0x9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);